### ISSUE TITLE
Install Material for MkDocs

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#724]
Our GIN website is built with [Material for MkDocs.](https://squidfunk.github.io/mkdocs-material/)

1. Clone the main [Geobtaa](https://github.com/geobtaa/geobtaa.github.io) website and the [metadata repository](https://github.com/geobtaa/metadata) to your desktop
2. Follow the instructions on https://github.com/geobtaa/geobtaa.github.io to install and serve the GIN and Metadata sites locally.

**Comment by cleorose** [comment]
- cloned both repositories to my "work" directory (designated spot for all repos)
- made a conda environment btaa-website for website editing dependencies
- followed instructions to install modules and plugins for mkdocs and material in that environment
- made a new branch of geobtaa.github.io repo. branch name "archubs-recipe-edits"
- got stuck on step 3: "Change into the opengeometadata.github.io directory and type: mkdocs serve" because I can't locate that directory.
